---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-yearn-redis-replica
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 0.3Gi
  hostPath:
    path: /data/yearn-redis-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-yearn-redis-replica
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: pv-yearn-redis-replica
  resources:
    requests:
      storage: 0.3G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yearn-redis-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yearn-redis-replica
  template:
    metadata:
      labels:
        app: yearn-redis-replica
    spec:
      subdomain: replica
      containers:
      - name: redis
        image: redis:6.2.6-alpine
        command:
          - "redis-server"
        args:
          - "--replicaof"
          - "yearn-redis-primary.default.svc.cluster.local"
          - "6379"
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: "yearn-redis-replica-volume"
          mountPath: "/data"
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          tcpSocket:
            port: 6379
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: "yearn-redis-replica-volume"
        persistentVolumeClaim:
          claimName: "pvc-yearn-redis-replica"
---
apiVersion: v1
kind: Service
metadata:
  name: yearn-redis-replica
spec:
  type: ClusterIP
  selector:
    app: yearn-redis-replica
  ports:
  - name: redis
    port: 6379
    targetPort: 6379